### ISSUE TITLE
Stat Variable Taxonomy

### ISSUE THREAD

**Issue by dspoka** [datacommonsorg/schema#249]
Hi I was wondering if its possible to get the stat var taxonomy like shown in the table here: https://www.datacommons.org/tools/statvar

Sorry if this is not the place/basic question.

**Comment by pradh** [comment]
Hi @dspoka -- the information on that page is constructed by a combination of our public [APIs](https://docs.datacommons.org/).  For examples:
- [Geting all triples in a stat var](https://api.datacommons.org/node/triples?dcids=Count_Person)
- [Summary info about a stat var](https://api.datacommons.org/stat-var/summary?stat_vars=Count_Person) (this API is not documented yet)

I'm curious to know more about what you're trying to do?

**Comment by dspoka** [comment]
Is there a place to get all statVars such that I can then choose which ones to get the summary info on? 

Im working climate science information extraction and was interested in the types of stat variables you have codified.

**Comment by pradh** [comment]
You could get a list of all StatVars from this schema repo.

For instance, with something like `awk '{ if ($1=="Node:") { gsub(/dcid:/, "", $2); print $2; } }' stat_vars/*.mcf`, or by using the [MCF parser](https://github.com/datacommonsorg/tools/tree/master/kg_util#mcf-parser).

**Comment by dspoka** [comment]
Using parser and your one liner both work. Thanks!
